#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         3
bspc config window_gap           10
bspc config active_border_color  "#000000"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a qutebrowser desktop='^3'
bspc rule -a signal-desktop desktop='^4'
