sxhkd &
compton &
xfce4-power-manager &
xrdb ~/.Xresources &
nm-applet &
xfce4-power-manager &
xinput --disable 10
feh --bg-fill ~/Pictures/backgrounds/purpmacish.jpg
setxkbmap -option grp:alt_shift_toggle us,ru && xmodmap ~/.Xmodmap &
exec bspwm
